### PR TITLE
Game Update 14 & QOL

### PR DESCRIPTION
**Pull request by JanThomasUP**
Sorry for the combined PR but:

the current dev branch is out of sync of the current code base (last dev version misses the game update 14 changes)
QOL 1: mods folder is now optional in /My Documents/Anno 1800/mods (besides the user savegames)
QOL 2: mods are now documented in {mods_origin}/.meta/history.log this way mods can now be associated with save-games

### CODE REVIEW

**Comment by xyrus02** [comment]
Does this mean the signature for GU 14 is still the same?

**Comment by JanThomasUP** [comment]
Just the comment was wrong the gu14 sig was already there and correct

**Comment by xforce** [comment]
I like the additional mod location.
However I have to think more about the other change, I think there is something better that can be done there instead of that.

Would you mind splitting this PR and create an issue regarding the `history.log` with some information on what, why etc. so we can discuss further?

**Comment by JanThomasUP** [comment]
Will split the PR till tomorrow and provide a showcase/additional infos for the history log. Thx for the feedback & consideration

**Pull request closed without merging**
